### ISSUE TITLE
Failed to compile on M1 Mac

### ISSUE THREAD

**Issue by LeeeSe** [webonnx/wonnx#137] opened 2023-01-13 13:49 UTC
**Describe the bug**
I only ran the following four lines of code, and then a compile error occurred

`cargo new wonnx_test`
`cd wonnx_test`
`cargo add wonnx`
`cargo run`

   Compiling wonnx v0.3.0
error[E0597]: `node` does not live long enough
   --> /Users/ls/.cargo/registry/src/github.com-1ecc6299db9ec823/wonnx-0.3.0/src/ir.rs:123:59
    |
96  |   impl<'model> Node<'model> {
    |        ------ lifetime `'model` defined here
...
123 |           let inputs: Result<Vec<Input<'model>>, IrError> = node
    |  ___________________________________________________________^
124 | |             .get_input()
    | |                        ^
    | |                        |
    | |________________________borrowed value does not live long enough
    |                          argument requires that `node` is borrowed for `'model`
...
179 |       }
    |       - `node` dropped here while still borrowed

 - OS: macOS 13.1 
 - rustc 1.66.1 (90743e729 2023-01-10)

**Comment by pixelspark** [comment] 2023-01-17 19:37
Yes, can reproduce. Looks like v0.3.0 is not compatible with Rust 1.66.1. The current master compiles just fine.

@haixuanTao can we publish a new version?

**Comment by pixelspark** [comment] 2023-03-06 08:47
This should be fixed in v0.4.0 which was released yesterday. @LeeeSe feel free to reopen if you still experience issues.

**Closed by pixelspark** 2023-03-06 08:47 UTC
